#############################################################################
# Makefile for building: TqcVisualOdemetry.app/Contents/MacOS/TqcVisualOdemetry
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  TqcVisualOdemetry.pro
# Template: app
# Command: /Users/yinghuang/Qt/5.7/clang_64/bin/qmake -spec macx-xcode -o TqcVisualOdemetry.xcodeproj/project.pbxproj TqcVisualOdemetry.pro
#############################################################################

MAKEFILE      = project.pbxproj

MOC       = /Users/yinghuang/Qt/5.7/clang_64/bin/moc
UIC       = /Users/yinghuang/Qt/5.7/clang_64/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
INCPATH       = -I. -I/usr/local/include -I/Users/yinghuang/Qt/Examples/QGLView/libQGLViewer-2.6.4/QGLViewer/QGLViewer.framework/Headers -I../../../ORB_SLAM/ORB_SLAM2_for_osx/eigen-3.3-rc1 -I../../../g2o_ba_example/g2o-master/g2o/solvers/cholmod -I../../../g2o_ba_example/g2o-master -I../../../g2o_ba_example/g2o-master/build -I../../../g2o_ba_example/SuiteSparse/SuiteSparse_config -I../../../g2o_ba_example/SuiteSparse/CHOLMOD/Include -I／usr/local/include -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtOpenGL.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtXml.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Users/yinghuang/Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/yinghuang/Qt/5.7/clang_64/lib
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: moc_TqcScene.cpp moc_VoMainWindow.cpp moc_OutputDialog.cpp\
	 moc_TqcThread.cpp moc_MatchDialog.cpp ui_vomainwindow.h ui_OutputDialog.h ui_MatchDialog.h
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_TqcScene.cpp moc_VoMainWindow.cpp moc_OutputDialog.cpp moc_TqcThread.cpp moc_MatchDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_TqcScene.cpp moc_VoMainWindow.cpp moc_OutputDialog.cpp moc_TqcThread.cpp moc_MatchDialog.cpp
moc_TqcScene.cpp: /Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		TqcScene.h \
		/Users/yinghuang/Qt/5.7/clang_64/bin/moc
	/Users/yinghuang/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/yinghuang/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/yinghuang/development/hy_code/SLAM/TqcSLAM/VisualOdemetry/TqcVisualOdemetry -I/usr/local/include -I/Users/yinghuang/Qt/Examples/QGLView/libQGLViewer-2.6.4/QGLViewer/QGLViewer.framework/Headers -I/Users/yinghuang/development/hy_code/SLAM/ORB_SLAM/ORB_SLAM2_for_osx/eigen-3.3-rc1 -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/g2o-master/g2o/solvers/cholmod -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/g2o-master -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/g2o-master/build -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/SuiteSparse/SuiteSparse_config -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/SuiteSparse/CHOLMOD/Include -I/Users/yinghuang/development/hy_code/SLAM/TqcSLAM/VisualOdemetry/TqcVisualOdemetry/／usr/local/include -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtOpenGL.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtXml.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks (framework directory)' -F/Users/yinghuang/Qt/5.7/clang_64/lib TqcScene.h -o moc_TqcScene.cpp

moc_VoMainWindow.cpp: /Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QToolButton \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		../../../g2o_ba_example/g2o-master/g2o/core/sparse_optimizer.h \
		TqcCamera.h \
		/usr/local/include/opencv2/core/utility.hpp \
		TqcEncodeDecode.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/libavutil/opt.h \
		/usr/local/include/libavcodec/avcodec.h \
		/usr/local/include/libavformat/avformat.h \
		/usr/local/include/libavutil/avutil.h \
		/usr/local/include/libswscale/swscale.h \
		TqcScene.h \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		OutputDialog.h \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		TqcDefines.h \
		TqcTypes.h \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QQueue \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		../../../g2o_ba_example/g2o-master/g2o/core/block_solver.h \
		../../../g2o_ba_example/g2o-master/g2o/core/robust_kernel.h \
		../../../g2o_ba_example/g2o-master/g2o/core/robust_kernel_impl.h \
		../../../g2o_ba_example/g2o-master/g2o/core/optimization_algorithm_levenberg.h \
		../../../g2o_ba_example/g2o-master/g2o/solvers/cholmod/linear_solver_cholmod.h \
		../../../g2o_ba_example/g2o-master/g2o/types/slam3d/se3quat.h \
		../../../g2o_ba_example/g2o-master/g2o/types/sba/types_six_dof_expmap.h \
		TqcDebugControl.h \
		../../../g2o_ba_example/g2o-master/g2o/types/slam3d/vertex_se3.h \
		../../../g2o_ba_example/g2o-master/g2o/core/optimizable_graph.h \
		MatchDialog.h \
		TqcBundleAdjust.h \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMutex \
		TqcThread.h \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		VoMainWindow.h \
		/Users/yinghuang/Qt/5.7/clang_64/bin/moc
	/Users/yinghuang/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/yinghuang/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/yinghuang/development/hy_code/SLAM/TqcSLAM/VisualOdemetry/TqcVisualOdemetry -I/usr/local/include -I/Users/yinghuang/Qt/Examples/QGLView/libQGLViewer-2.6.4/QGLViewer/QGLViewer.framework/Headers -I/Users/yinghuang/development/hy_code/SLAM/ORB_SLAM/ORB_SLAM2_for_osx/eigen-3.3-rc1 -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/g2o-master/g2o/solvers/cholmod -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/g2o-master -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/g2o-master/build -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/SuiteSparse/SuiteSparse_config -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/SuiteSparse/CHOLMOD/Include -I/Users/yinghuang/development/hy_code/SLAM/TqcSLAM/VisualOdemetry/TqcVisualOdemetry/／usr/local/include -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtOpenGL.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtXml.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks (framework directory)' -F/Users/yinghuang/Qt/5.7/clang_64/lib VoMainWindow.h -o moc_VoMainWindow.cpp

moc_OutputDialog.cpp: /Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		TqcDefines.h \
		TqcTypes.h \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QQueue \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		../../../g2o_ba_example/g2o-master/g2o/core/sparse_optimizer.h \
		../../../g2o_ba_example/g2o-master/g2o/core/block_solver.h \
		../../../g2o_ba_example/g2o-master/g2o/core/robust_kernel.h \
		../../../g2o_ba_example/g2o-master/g2o/core/robust_kernel_impl.h \
		../../../g2o_ba_example/g2o-master/g2o/core/optimization_algorithm_levenberg.h \
		../../../g2o_ba_example/g2o-master/g2o/solvers/cholmod/linear_solver_cholmod.h \
		../../../g2o_ba_example/g2o-master/g2o/types/slam3d/se3quat.h \
		../../../g2o_ba_example/g2o-master/g2o/types/sba/types_six_dof_expmap.h \
		TqcDebugControl.h \
		../../../g2o_ba_example/g2o-master/g2o/types/slam3d/vertex_se3.h \
		../../../g2o_ba_example/g2o-master/g2o/core/optimizable_graph.h \
		OutputDialog.h \
		/Users/yinghuang/Qt/5.7/clang_64/bin/moc
	/Users/yinghuang/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/yinghuang/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/yinghuang/development/hy_code/SLAM/TqcSLAM/VisualOdemetry/TqcVisualOdemetry -I/usr/local/include -I/Users/yinghuang/Qt/Examples/QGLView/libQGLViewer-2.6.4/QGLViewer/QGLViewer.framework/Headers -I/Users/yinghuang/development/hy_code/SLAM/ORB_SLAM/ORB_SLAM2_for_osx/eigen-3.3-rc1 -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/g2o-master/g2o/solvers/cholmod -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/g2o-master -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/g2o-master/build -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/SuiteSparse/SuiteSparse_config -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/SuiteSparse/CHOLMOD/Include -I/Users/yinghuang/development/hy_code/SLAM/TqcSLAM/VisualOdemetry/TqcVisualOdemetry/／usr/local/include -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtOpenGL.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtXml.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks (framework directory)' -F/Users/yinghuang/Qt/5.7/clang_64/lib OutputDialog.h -o moc_OutputDialog.cpp

moc_TqcThread.cpp: /Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		TqcThread.h \
		/Users/yinghuang/Qt/5.7/clang_64/bin/moc
	/Users/yinghuang/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/yinghuang/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/yinghuang/development/hy_code/SLAM/TqcSLAM/VisualOdemetry/TqcVisualOdemetry -I/usr/local/include -I/Users/yinghuang/Qt/Examples/QGLView/libQGLViewer-2.6.4/QGLViewer/QGLViewer.framework/Headers -I/Users/yinghuang/development/hy_code/SLAM/ORB_SLAM/ORB_SLAM2_for_osx/eigen-3.3-rc1 -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/g2o-master/g2o/solvers/cholmod -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/g2o-master -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/g2o-master/build -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/SuiteSparse/SuiteSparse_config -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/SuiteSparse/CHOLMOD/Include -I/Users/yinghuang/development/hy_code/SLAM/TqcSLAM/VisualOdemetry/TqcVisualOdemetry/／usr/local/include -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtOpenGL.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtXml.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks (framework directory)' -F/Users/yinghuang/Qt/5.7/clang_64/lib TqcThread.h -o moc_TqcThread.cpp

moc_MatchDialog.cpp: /Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		TqcTypes.h \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers/QQueue \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		../../../g2o_ba_example/g2o-master/g2o/core/sparse_optimizer.h \
		../../../g2o_ba_example/g2o-master/g2o/core/block_solver.h \
		../../../g2o_ba_example/g2o-master/g2o/core/robust_kernel.h \
		../../../g2o_ba_example/g2o-master/g2o/core/robust_kernel_impl.h \
		../../../g2o_ba_example/g2o-master/g2o/core/optimization_algorithm_levenberg.h \
		../../../g2o_ba_example/g2o-master/g2o/solvers/cholmod/linear_solver_cholmod.h \
		../../../g2o_ba_example/g2o-master/g2o/types/slam3d/se3quat.h \
		../../../g2o_ba_example/g2o-master/g2o/types/sba/types_six_dof_expmap.h \
		MatchDialog.h \
		/Users/yinghuang/Qt/5.7/clang_64/bin/moc
	/Users/yinghuang/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/yinghuang/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/yinghuang/development/hy_code/SLAM/TqcSLAM/VisualOdemetry/TqcVisualOdemetry -I/usr/local/include -I/Users/yinghuang/Qt/Examples/QGLView/libQGLViewer-2.6.4/QGLViewer/QGLViewer.framework/Headers -I/Users/yinghuang/development/hy_code/SLAM/ORB_SLAM/ORB_SLAM2_for_osx/eigen-3.3-rc1 -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/g2o-master/g2o/solvers/cholmod -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/g2o-master -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/g2o-master/build -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/SuiteSparse/SuiteSparse_config -I/Users/yinghuang/development/hy_code/SLAM/g2o_ba_example/SuiteSparse/CHOLMOD/Include -I/Users/yinghuang/development/hy_code/SLAM/TqcSLAM/VisualOdemetry/TqcVisualOdemetry/／usr/local/include -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtOpenGL.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtXml.framework/Headers -I/Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks (framework directory)' -F/Users/yinghuang/Qt/5.7/clang_64/lib MatchDialog.h -o moc_MatchDialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_vomainwindow.h ui_OutputDialog.h ui_MatchDialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_vomainwindow.h ui_OutputDialog.h ui_MatchDialog.h
ui_vomainwindow.h: vomainwindow.ui \
		/Users/yinghuang/Qt/5.7/clang_64/bin/uic
	/Users/yinghuang/Qt/5.7/clang_64/bin/uic vomainwindow.ui -o ui_vomainwindow.h

ui_OutputDialog.h: OutputDialog.ui \
		/Users/yinghuang/Qt/5.7/clang_64/bin/uic
	/Users/yinghuang/Qt/5.7/clang_64/bin/uic OutputDialog.ui -o ui_OutputDialog.h

ui_MatchDialog.h: MatchDialog.ui \
		/Users/yinghuang/Qt/5.7/clang_64/bin/uic
	/Users/yinghuang/Qt/5.7/clang_64/bin/uic MatchDialog.ui -o ui_MatchDialog.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

