#############################################################################
# Makefile for building: TqcVisualOdemetry.app/Contents/MacOS/TqcVisualOdemetry
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  TqcVisualOdemetry.pro
# Template: app
# Command: /Users/yinghuang/Qt/5.7/clang_64/bin/qmake -spec macx-xcode -o project.pbxproj TqcVisualOdemetry.pro
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /Users/yinghuang/Qt/5.7/clang_64/bin/qmake
project.pbxproj: TqcVisualOdemetry.pro /Users/yinghuang/Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf /Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/qdevice.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/common/unix.conf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/common/mac.conf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/common/macx.conf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/common/clang.conf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/qconfig.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/macx-xcode/qmake.conf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/qt.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/resources.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/moc.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/uic.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/lex.prf \
		TqcVisualOdemetry.pro \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtXml.framework/QtXml.prl \
		/Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-xcode -o project.pbxproj TqcVisualOdemetry.pro
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/spec_pre.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/qdevice.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/device_config.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/common/unix.conf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/common/mac.conf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/common/macx.conf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/common/sanitize.conf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/common/gcc-base.conf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/common/clang.conf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/common/clang-mac.conf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/qconfig.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/qt_functions.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/qt_config.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/macx-xcode/qmake.conf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/default_pre.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/resolve_config.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/default_post.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/warn_on.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/qt.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/resources.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/moc.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/uic.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/unix/thread.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/file_copies.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/mac/rez.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/exceptions.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/yacc.prf:
/Users/yinghuang/Qt/5.7/clang_64/mkspecs/features/lex.prf:
TqcVisualOdemetry.pro:
/Users/yinghuang/Qt/5.7/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/yinghuang/Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/yinghuang/Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/yinghuang/Qt/5.7/clang_64/lib/QtXml.framework/QtXml.prl:
/Users/yinghuang/Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-xcode -o project.pbxproj TqcVisualOdemetry.pro

qmake_all: FORCE

